version: "3"

services:
  # PostgreSQL for keycloak
  secured-identity-db:
    container_name: secured-identity-db
    image: postgres:16-alpine
    ports:
      - 6063:5432
    expose:
      - 6063
    volumes:
      - ./data/secured-identity-db:/var/lib/postgresql/data
    restart: always
    environment:
      - POSTGRES_PASSWORD=myStrongPassword123
      - POSTGRES_USER=keycloak
      - POSTGRES_DB=keycloak
    networks:
      - secured-network

  # Keycloak
  secured-identity:
    container_name: secured-identity
    build: ./Identity
    command: ["start-dev"]
    ports:
      - 5053:8080
    expose:
      - 5053
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
      - KC_HOSTNAME_URL=http://localhost:5050/identity
      - KC_DB=postgres
      - KC_DB_USERNAME=keycloak
      - KC_DB_PASSWORD=myStrongPassword123
      - KC_DB_URL=jdbc:postgresql://secured-identity-db:5432/keycloak
    depends_on: 
      - secured-identity-db
    networks:
      - secured-network

networks:
  secured-network:
    driver: bridge

volumes:
  secured-data:
    driver: local